---
- name: "Create inventory with target host(s)"
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - include_role:
        name: inventory_helper
        tasks_from: create_single_host_inventory.yml

- name: "Install - FabOS Device"
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - ansible.builtin.include_role:
        name: "node_exporter"

- name: Delegate resource-id to all
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: Delegate resource-id
      ansible.builtin.set_fact:
        resource_id: "{{ resource_id }}"
      delegate_facts: true
      delegate_to: "{{ item }}"
      loop: "{{ groups['all'] }}"

- name: "Add host to Prometheus targets"
  hosts: all
  gather_facts: no
  become: no
  vars:
    ansible_connection: local
  tasks:
    - ansible.builtin.include_role:
        name: "prometheus"
        tasks_from: add_target.yml
      vars:
        node_exporter_port: 9100
