---
- name: Verify uninstall
  hosts: target_host
  gather_facts: no
  tasks:
    - name: Check ports unavailable
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ item }}"
        timeout: 30
        state: absent
      loop:
        - "9100"
        - "4001"
        - "8500"