---
- name: Assert Input params
  ansible.builtin.assert:
    that:
      - resource_id is defined and resource_id | length > 0
      - node_exporter_port is defined

- name: "Add resource with id = \"{{ resource_id }}\", address = \"{{ ansible_host }}\" and port = \"{{ node_exporter_port }}\""
  ansible.builtin.uri:
    url: "http://{{ prometheus_configurator_host_name }}:{{ prometheus_configurator_port }}/prometheus/slm-resource-target"
    method: POST
    body_format: form-urlencoded
    body:
      slm_id: "{{ resource_id }}"
      url: "{{ ansible_host }}:{{ node_exporter_port }}"

